### PR TITLE
added attributes.cc

### PR DESCRIPTION
**Pull request by xetra11**
I made attribute classes now concrete with getter / setter

Sorry for junk files .cc~ and .gch

I forgot to setup my gitignore right. Next time wont happen

### CODE REVIEW

**Comment by drummyfish** [comment]
Don't be sorry and remove those files please :D I'll look at the code later today.

**Comment by drummyfish** [comment]
OK looks nice :) Just a few things that need fixing:
- The junk files have to go.
- Use method_name convention instead of methodName (setters and getters), camels only for class names.
- What does p_ prefix in attribute names such as p_strength mean? Name it simply strength, don't use abbreviations. The parameters can have the same names as the class member attributes, "this->will_power = will_power" works fine.
- Why are rapidxml headers changed? They shouldn't be, or it should be mentioned why that is.

**Comment by xetra11** [comment]
Ok will change the method names.
p_prefix was meant to signalize a parameter_varname
Didnt knew this-> is possible in c++ so I gonna use that now.

rapidxml...well I saw it has been changed but dunno why didnt did anything to it tbh. But if you can see there wasnt a real change - a delete and reset so the files shouldnt be changed actually. mybe it was because of my "git rm --cache *" because I had to delete my cache to apply new gitignore rules

**Comment by xetra11** [comment]
alright fixed the issues. the rapidxml stuff seems to emerge when I merge my experimental branch - but it shouldnt be a problem because it in fact did not changed at all

**Comment by drummyfish** [comment]
I'm still seeing rapidxml files are changed in the commit compared to my branch, I'll try to resolve it but next time only commit files that should be commited, you don't have to commit everything that you changed. If by some accident you change some files that you didn't want to and you bury them under a lot of commits, I think you should pull the original files from my branch before making the pull request.

**Pull request merged**
