### PR TITLE
Added combat.c and combat.cc

### PR DESCRIPTION
**Pull request by xetra11**
Please check if its all good

### CODE REVIEW

**Comment by drummyfish** [comment]
looks OK, I'll test and merge

**Comment by drummyfish** [comment]
although having pointer to pointer as a pointer to array doesn't make sense without also having the array length... I'll change it to vector of pointers

**Comment by drummyfish** [comment]
also ComabtScene has array of participants, not only one participants, I'll also change that

**Comment by drummyfish** [comment]
being = being; should be this->being = being;

**Comment by xetra11** [comment]
"being = being; should be this->being = being;"

Why ?

since being is a pointer var member in this and the parameter for setBeing is a pointer of Being as well I dont need to access it with -> do I ?

isnt "this" implicitly meant when I say "being = being" ?

I know that inside the function the reference to its owning project is deliver through a pointer implcitly...

so "setBeing(CombatParticipant\* this, Being\* being)" is the real hidden function signature.

---

And if I'm wrong - what I'm sure of :dancer: 

"void CombatParticipant::set_combat_scene(CombatScene\* combat_scene)
  {
    combat_scene = combat_scene;
  }
"

why did you not tell me that here should be an -> as well?

sry for questioning so much

**Pull request merged**
